# Generated by Django 3.2.6 on 2021-08-27 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='is_public')),
                ('is_rated', models.BooleanField(default=True, verbose_name='is_public')),
                ('is_timed', models.BooleanField(default=True, verbose_name='is_public')),
                ('game_timer', models.IntegerField(default=1, verbose_name='game_timer')),
                ('move_timer', models.IntegerField(default=1, verbose_name='move_timer')),
                ('player_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
