# Generated by Django 3.2.6 on 2021-08-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_rated',
            field=models.BooleanField(default=True, verbose_name='is_rated'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_timed',
            field=models.BooleanField(default=True, verbose_name='is_timed'),
        ),
        migrations.AlterField(
            model_name='game',
            name='move_timer',
            field=models.IntegerField(default=30, verbose_name='move_timer'),
        ),
    ]
