# Generated by Django 3.2.6 on 2021-08-28 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_1',
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ManyToManyField(related_name='player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_2',
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ManyToManyField(related_name='player_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
