# Generated by Django 3.2.6 on 2021-08-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210828_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='side',
            field=models.CharField(blank=True, max_length=10, verbose_name='side'),
        ),
    ]
