# Generated by Django 3.2.6 on 2021-08-29 06:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=9), blank=True, default=list, size=10),
        ),
    ]
