# Generated by Django 3.2.6 on 2021-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210829_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_turn',
            field=models.IntegerField(default=-1, verbose_name='player_turn'),
        ),
    ]
