# Generated by Django 3.2.6 on 2021-09-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210831_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='connected_player',
            field=models.IntegerField(default=0, verbose_name='connected_player'),
        ),
    ]
