# Generated by Django 3.2.6 on 2021-09-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='winning_percentage',
            field=models.FloatField(default=0, verbose_name='winning_percentage'),
        ),
    ]
