# Generated by Django 3.2.6 on 2021-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='draw_count',
            field=models.IntegerField(default=0, verbose_name='draw_count'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='games_played_count',
            field=models.IntegerField(default=0, verbose_name='games_played_count'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='losses_count',
            field=models.IntegerField(default=0, verbose_name='losses_count'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='winning_percentage',
            field=models.IntegerField(default=0, verbose_name='winning_percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins_count',
            field=models.IntegerField(default=0, verbose_name='wins_count'),
        ),
    ]
