# Generated by Django 3.2.6 on 2021-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_winning_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games_played_count',
            field=models.FloatField(default=0, verbose_name='games_played_count'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins_count',
            field=models.FloatField(default=0, verbose_name='wins_count'),
        ),
    ]
