# Generated by Django 3.2.6 on 2021-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210901_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='draw_count',
            field=models.FloatField(default=0, verbose_name='draw_count'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='losses_count',
            field=models.FloatField(default=0, verbose_name='losses_count'),
        ),
    ]
